# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.URLField(),
        ),
    ]
